image: Visual Studio 2019

version: 1.0.{build}

environment:
  SONAR_TOKEN:
    secure: c6IKYB2JPnRQUNahHFnh8vAmkorjL8rrQ69EhkHkrgC3qsg2xyd7kGSM6kHzoMqZ
  GITHUB_ACCESS_TOKEN:
    secure: 0N79FChOALIaVLqCj5aJn6LnTfS05SZpEXFGCLap73GzFqbAA0BGh2OHPH2sqFWg

branches:
  only:
    - master

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

configuration: Release
platform: Any CPU

notifications:
- provider: Slack
  auth_token:
    secure: Y3i58yrHTt57qU64K8VsB06JMBZr7+9I44tYOd3oyWKnR+vpDilZKpiblJgwM2jHUQ88DzmBaeYzQIS9cA00oaamvT+zc/XizDsL7QBbisE=
  channel: '#build-opensource'


install:
  # compute version
  - ps: wget "https://raw.githubusercontent.com/rducom/ALM/master/build/ComputeVersion.ps1" -outfile "ComputeVersion.ps1"
  - ps: . .\ComputeVersion.ps1
  - ps: $version = Compute "src\MerQure\MerQure.csproj" $env:APPVEYOR_BUILD_NUMBER $env:APPVEYOR_REPO_TAG $env:APPVEYOR_PULL_REQUEST_NUMBER
  - ps: Update-AppveyorBuild -Version $version.Semver
  - dotnet tool install --global dotnet-sonarscanner 
  - dotnet tool install --global dotnet-reportgenerator-globaltool
  - dotnet tool install --global Codecov.Tool

before_build:
- dotnet restore
- cmd: >-
    IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (
    dotnet sonarscanner begin /k:"MerQure" /d:"sonar.host.url=https://sonarcloud.io" /o:lucca /d:"sonar.login=%SONAR_TOKEN%" /d:sonar.coverageReportPaths="./sonarCoverage/SonarQube.xml"
    ) ELSE (
    dotnet sonarscanner begin /k:"MerQure" /d:"sonar.host.url=https://sonarcloud.io" /o:lucca /d:"sonar.login=%SONAR_TOKEN%" /d:sonar.coverageReportPaths="./sonarCoverage/SonarQube.xml" /d:"sonar.github.oauth=%GITHUB_ACCESS_TOKEN%" /d:"sonar.pullrequest.provider=github" /d:"sonar.pullrequest.branch=%APPVEYOR_REPO_BRANCH%" /d:"sonar.pullrequest.key=%APPVEYOR_PULL_REQUEST_NUMBER%" /d:"sonar.pullrequest.github.repository=LuccaSA/MerQure" /d:"sonar.pullrequest.github.endpoint=https://api.github.com"
    )

build_script:
- ps: dotnet build MerQure.sln -c Debug -v minimal

test_script:
- dotnet test -f netcoreapp3.1 /p:DebugType=full -c Debug --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory:./coverage
- reportgenerator -reports:./coverage/*/*.xml -targetdir:./sonarCoverage -reporttypes:SonarQube
- dotnet sonarscanner end /d:"sonar.login=%SONAR_TOKEN%"
- codecov -f "coverage/**/*.xml"

after_test:
- ps: dotnet pack src\MerQure\MerQure.csproj --include-symbols /p:$("VersionPrefix="+$version.Prefix+";VersionSuffix="+$version.Suffix) /p:Configuration=Release /p:SourceLinkEnabled=true /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION -o ..\..\artifacts
- ps: dotnet pack src\MerQure.RbMQ\MerQure.RbMQ.csproj --include-symbols /p:$("VersionPrefix="+$version.Prefix+";VersionSuffix="+$version.Suffix) /p:Configuration=Release /p:SourceLinkEnabled=true /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION -o ..\..\artifacts
- ps: dotnet pack src\MerQure.Tools\MerQure.Tools.csproj --include-symbols /p:$("VersionPrefix="+$version.Prefix+";VersionSuffix="+$version.Suffix) /p:Configuration=Release /p:SourceLinkEnabled=true /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION -o ..\..\artifacts

artifacts:
  - path: .\artifacts\**\*.nupkg
    name: lib

deploy:

- provider: NuGet
  api_key:
    secure: UEuJPMHE7Wh7Sk2xUDH+vUL2NTDFgwKDMfSS1MztitwhNUUZfUYJGYvlFPcJSx9m
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    deploy_public: true

- provider: NuGet
  server: https://ci.appveyor.com/nuget/luccaintegration-uvk5yq2c460b/api/v2/package
  api_key:
    secure: shmMXUHQLw1te1msoPnFzFFxFEo2lLWF4wriUUAwOaY=
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    deploy_unstable: true
