pull_requests:  
  do_not_increment_build_number: true

before_build:
- nuget restore

build:
  project: src\MerQure.sln
  
notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: mIWjgBPlebPHnHk+SkKhZqHOkD6LIZrh1tnOq+f9pWxASTTvlwmAEgZF3kvH6Em6
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
